Feature: Global preferences
  As a user
  I want to configure global preferences
  So that Vibe Kanban matches my workflow

  Scenario: Change theme
    Given I am on the Settings page
    When I select the light or dark theme
    Then the application updates to the chosen theme

  Scenario: Change language
    Given I am on the Settings page
    When I select a language or browser default
    Then the UI uses the selected language preference

  Scenario: Set the default agent configuration
    Given I am on the Settings page
    When I choose a default agent and variant
    Then new task attempts preselect that configuration

  Scenario: Configure a branch prefix
    Given I am on the Settings page
    When I set a valid branch prefix
    Then autogenerated task branches include the prefix

  Scenario: Invalid branch prefix is rejected
    Given I am on the Settings page
    When I enter an invalid branch prefix (e.g., containing '/')
    Then I see a validation error
    And the prefix is not saved

  Scenario: Configure PR auto-description behavior
    Given I am on the Settings page
    When I enable auto-generate PR descriptions and set a custom prompt
    Then new PRs use the default auto-description setting and prompt

  Scenario: Enable or disable telemetry
    Given I am on the Settings page
    When I toggle telemetry on or off
    Then Vibe Kanban saves my privacy preference

  Scenario: Reset onboarding and safety acknowledgments
    Given I am on the Settings page
    When I reset onboarding or the safety disclaimer
    Then the corresponding onboarding or disclaimer flow is shown again
